<Project Sdk="Godot.NET.Sdk/4.5.1" InitialTargets="CheckDependencyPaths">
  <Import Project=".\Sts2PathDiscovery.props"/>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>FoolsGambit</AssemblyName>
    <Version>0.1.0</Version>
    <ImplicitUsings>true</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Publicize>false</Publicize>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
    <PathMap>$(AppOutputBase)=.\</PathMap>
    <GodotDisabledSourceGenerators>GodotPluginsInitializer</GodotDisabledSourceGenerators>
    <NoWarn>$(NoWarn);MSB3270</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition="Exists('$(Sts2DataDir)')">
    <Reference Include="0Harmony">
      <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="sts2">
      <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Alchyr.Sts2.BaseLib" Version="3.3.8" PrivateAssets="All"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="FoolsGambit/**"/>
    <EmbeddedResource Remove="FoolsGambit/**"/>
    <None Include="FoolsGambit.json"/>
    <None Include="project.godot"/>
    <None Include="FoolsGambit/**"/>
  </ItemGroup>

  <Target Name="CheckDependencyPaths">
    <Error Text="Slay the Spire 2 data not found at path '$(Sts2DataDir)'"
           Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')"/>
  </Target>

  <Target Name="CopyToModsFolderOnBuild" AfterTargets="PostBuildEvent" Condition="'$(InstallToGame)' == 'true'">
    <MakeDir Directories="$(ModsPath)$(MSBuildProjectName)/"/>
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
    <Copy SourceFiles="$(AssemblyName).json" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" Condition="Exists('$(TargetDir)$(TargetName).pdb')"/>
  </Target>

  <Target Name="NeedGodotForPublish" BeforeTargets="Publish">
    <Error Text="Godot path must be set before publishing."
           Condition="'$(GodotPath)' == '' or !Exists('$(GodotPath)')"/>
  </Target>

  <Target Name="GodotImportAssets" Condition="'$(GodotPath)' != '' and Exists('$(GodotPath)') and '$(IsInnerGodotExport)' != 'true'">
    <Exec Command="&quot;$(GodotPath)&quot; --headless --path &quot;$(MSBuildProjectDirectory)&quot; --import"
          EnvironmentVariables="IsInnerGodotExport=true;MSBUILDDISABLENODEREUSE=1"/>
  </Target>

  <Target Name="GodotPublish" AfterTargets="Publish" DependsOnTargets="GodotImportAssets"
          Condition="'$(GodotPath)' != '' and Exists('$(GodotPath)') and '$(IsInnerGodotExport)' != 'true'">
    <MakeDir Directories="$(ModsPath)$(MSBuildProjectName)/"/>
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
    <Copy SourceFiles="$(AssemblyName).json" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
    <Exec Command="&quot;$(GodotPath)&quot; --headless --path &quot;$(MSBuildProjectDirectory)&quot; --export-pack &quot;BasicExport&quot; &quot;$(ModsPath)$(MSBuildProjectName)/$(MSBuildProjectName).pck&quot;"
          EnvironmentVariables="IsInnerGodotExport=true;MSBUILDDISABLENODEREUSE=1"/>
  </Target>
</Project>
